<h2>Az alapítványról</h2>
<img src="./images/rexlogo.jpg">
<h3>A Rex Alapítvány küldetése</h3>
<p>Üdvözlünk a Rex Kutyaotthon Alapítvány honlapján! Alapítványunk az ember és az állatok harmonikus együttélésének biztosítását, a felelős állattartásra való nevelést, a kóbor állatok létszámának csökkentését, valamint  az állatok szenvedésének megakadályozását tűzte ki célul. Az idén 27 éves Rex Kutyaotthon Alapítvány napi szinten több mint 250 elhagyott, sebesült, krízishelyzetben lévő állatnak nyújt segítséget. Tesszük mindezt azért, mert úgy gondoljuk az élet minden formája tiszteletre, megbecsülésre és így védelemre méltó. Mindennapi feladatunk egy civilizált színvonalú állatvédelmi szolgálat fenntartása nyilvános állatvédelmi irodánk, állatörökbefogadási központunk és állatmentő szolgálatunk  működtetése révén. Alapítványunk telephelye egy többfunkciós létesítmény - a Budapesti Állatvédelmi és Természetvédelmi Élménypark - rövid nevén Rex Állatsziget - mely egyaránt szolgálja az állatvilág jobb megismertetését, a helyes állattartási kultúra kialakítását,  és  a környezettudatos magatartás népszerűsítését. </p>
<p> Hosszú távú célunk az, hogy minél kevesebb állat szoruljon segítségre, ezért aktívan dolgozunk azért, hogy a felelős állattartás és az állatvédelem magától értetődővé váljon Magyarországon. A Rex Állatszigetet a nagyközönség számára nyitott állat- és természetvédelmi élményparkká alakítottuk, ahol bárki megismerkedhet az állatokkal való együttélés alapjaival. A Rex Állatszigeten a Társállat-örökbefogadási központ mellett létrehoztunk egy Vizes élőhelyet, egy Minifarmot és egy Oktatóközpontot is, idén pedig megépült a bajbajutott vadállatokat segítő Vadmentő Állomásunk. </p>
<h3>Az alapító üzenete</h3>
<p>"Amennyire vissza tudok emlékezni, kiskoromban csupa olyan dologra vágyakoztam, melyeket józan ésszel nemigen lehetett véghezvinni, mégis erősen hittem azok megvalósulásában.  A serdülőkorba lépve már reálisabb célokat tűztem ki magam elé, de így is számos kudarc ért. Felnőttként immár sokkal visszafogottabban kezelem vágyaimat, hogy megkíméljem magam az újabb csalódásoktól. </p>
<p>Ha azonban, az állatokról van szó, most is elragad a hév, és képes vagyok gyermekként álmodozni egy olyan világról, melyben az állatokat megbecsülés övezi. Kicsiben ilyen világ a mi állatszigetünk is, ahol az állatok szeretetét és tiszteletét nem csak gyakoroljuk, hanem tanítjuk is  A Rex alapítvány felcseperedésével és az állatsziget létrejöttével egy régi álmom valósult meg. Szerencsés embernek mondhatom magam, hisz az álmodásban és az álmok életrehívásában rengetegen segítenek,  akikhez képest az ellendrukkerek száma elenyésző.  Wass Albert szerint gyerekké kell válnunk ahhoz, hogy felnőtté válhassunk. Ezért egyre gyakrabban idézem vissza azokat az időket, amikor még teljesen nyitott szívvel, gyanakvás és fenntartások nélkül fogadtam minden emberi közeledést. Szükség is van rá, hisz  úgy érzem most jött el az ideje annak, hogy felnőttként is hinni tudjunk  egy olyan szellemiségben, amely abban segít, hogy mesterkélt érzelmek és rideg számítás nélkül tudjunk rátalálni olyan barátokra, akik nem akarnak mást és többet, csak egy kicsit jobbá tenni a világot! Dr. Király Péter, alapító" </p>

